### ISSUE TITLE
Functional?

### ISSUE THREAD

**Issue by SoffiMeower** [obhq/firmware-dumper#2]
Is this payload functional yet? It doesn't seem to give any notification for activity when I injected the payload using Payload Guest

**Comment by SoffiMeower** [comment]
@ultimaweapon

**Comment by ultimaweapon** [comment]
Not yet. That why I did not make a CI to let the user download yet.

**Comment by ultimaweapon** [comment]
This is unlikely to functional soon because my current focus is migrating the user-mode kernel to kernel-mode kernel. I'll comeback to work on this once the kernel-mode kernel need to mount rootfs.

**Comment by SoffiMeower** [comment]
> This is unlikely to functional soon because my current focus is migrating the user-mode kernel to kernel-mode kernel. I'll comeback to work on this once the kernel-mode kernel need to mount rootfs.

Well yeah, that's kinda the thing- Idk how to test the emulator without the new firmware dump LMAO

**Comment by ultimaweapon** [comment]
The current state is really not suitable for the users to test. I'll let you know when we are ready for the users to test.

**Comment by SoffiMeower** [comment]
Yeah, also is kinda hard for me to test as well LMAO-

**Comment by ultimaweapon** [comment]
The current version is intended to be used for development only. It is likely you will need to dump again for our first public release.
